// Generated by CoffeeScript 1.7.1
(function() {
  var button, insertRedLetter, showText, switchView, textArea, wordLabel;

  wordLabel = document.querySelector('h1');

  button = document.querySelector('button');

  textArea = document.querySelector('textarea');

  showText = function(text) {
    var word, _i, _len, _results;
    window.setTimeout(function() {
      return switchView(2);
    }, 5000);
    _results = [];
    for (_i = 0, _len = text.length; _i < _len; _i++) {
      word = text[_i];
      _results.push(wordLabel.innerHTML = insertRedLetter(word));
    }
    return _results;
  };

  button.addEventListener('click', function() {
    switchView(1);
    return showText(textArea.value.split(' '));
  });

  switchView = function(view) {
    if (view === 1) {
      wordLabel.style.display = '';
      textArea.style.display = 'none';
      return button.style.display = 'none';
    } else {
      wordLabel.style.display = 'none';
      textArea.style.display = '';
      return button.style.display = '';
    }
  };

  insertRedLetter = function(word) {
    var output, position;
    if (word.length === 1) {
      return word;
    } else {
      position = ~~(word.length / 2) - 1;
      return output = word.substr(0, position) + '<span style="color: red">' + word[position] + '</span>' + word.substr(position + 1);
    }
  };

}).call(this);
